const API_URL = 'http://localhost:8080/pg';

export const API_ROUTES = {
  displayImages: `${API_URL}/`,
  addMember: `${API_URL}/addMembers`,
  displayMember: `${API_URL}/display/members`,
  getVacancies: `${API_URL}/api/vacancies`,
  getAdvanceTickets: `${API_URL}/advance_tickets`,
  getPhoneNumbers: `${API_URL}/api/phone-numbers`,
  editMember: `${API_URL}/edit/member`,
  deleteMember: `${API_URL}/api/insertVacatingMember`,
  vacancies: `${API_URL}/api/vacancies`,
  availableBeds: `${API_URL}/api/available-beds`,
  dolwnloadAPK: `${API_URL}/download/myapp.apk`,
  shiftMember: `${API_URL}/api/shiftMember`,
  fetchBeds: `${API_URL}/beds`,
  addStatements: `${API_URL}/api/add/statements`,
  fetchStatements: `${API_URL}/api/statements`,
  calanderFetch: `${API_URL}/api/calendar`,
  fetchVeacatingMemberList: `${API_URL}/api/vacating-members`,
  displayFetchTotalRent: `${API_URL}/api/total-rent`,
  fetchLevingMemberList: `${API_URL}/api/leaving-members`,
  fetchMemberNotPaidRentList: `${API_URL}/api/rent-not-paid`,
  fetchJoiningMembersList: `${API_URL}/api/joining-members`,
  markRentPaidAPI: `${API_URL}/api/mark-rent-paid`,
  markRentNotPaidAPI: `${API_URL}/api/mark-rent-not-paid`,
  fetchListMemberRentPaid: `${API_URL}/api/members-paid-rent`,
  fetchSharingBedApiDETAILS: `${API_URL}/beds`,
  revertVacatingMember: `${API_URL}/api/vacating-members`,
  sendWhstappReminder: `${API_URL}/api/send-whatsapp-reminder`,
  fetchBuildingsAddBuildings: `${API_URL}/buildings/fetch`,
  fetchFloorsAddBuildings: `${API_URL}/floors/fetch`,
  fetchFlatsAddBuildings: `${API_URL}/flats/fetch`,
  fetchRoomsAddBuildings: `${API_URL}/rooms/fetch`,
  fetchBedsAddBuildings: `${API_URL}/beds/fetch`,
  addBuildings: `${API_URL}/buildings/add`,
  addFloor: `${API_URL}/floors/add`,
  addFlat: `${API_URL}/flats/add`,
  addRoom: `${API_URL}/rooms/add`,
  addBed: `${API_URL}/beds/add`,
  deleteBuilding: (id) => `${API_URL}/buildings/delete/${id}`,
  deleteFloor: (id) => `${API_URL}/floors/delete/${id}`,
  deleteFlat: (id) => `${API_URL}/flats/delete/${id}`,
  deleteRoom: (id) => `${API_URL}/rooms/delete/${id}`,
  deleteBed: (id) => `${API_URL}/beds/delete/${id}`,
};
